### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by mathiasrw** [Rich-Harris/HTMLX#16]
Just to let you know the website htmlx.org is not working at the moment.

**Comment by arxpoetica** [comment]
Where in this repository is htmlx.org listed as the website? I can't find it.

**Comment by mathiasrw** [comment]
Well.... actually it does not... I was just assuming from the name. Closing :)

![image](https://user-images.githubusercontent.com/1063454/80918522-bec4c000-8d65-11ea-9c1e-3d2b39d81570.png)
